update testplan content
erda-project/erda-proto pull request #167
Opened 2021-09-13 08:00 UTC by ZLValien

update testplan content

2021-09-13 08:05 UTC, sfwn requested changes

2021-09-13 08:05 UTC, sfwn commented on core/dop/autotest/testplan/autotest-plan.proto
> +  string executeDuration = 5;
duration should lbe int64 ?

2021-09-13 08:08 UTC, ZLValien commented on core/dop/autotest/testplan/autotest-plan.proto
> +  string executeDuration = 5;
duration is string like "01:10:01".
meaning 1h,10m,1s

2021-09-14 06:14 UTC, ZLValien commented on core/dop/autotest/testplan/autotest-plan.proto
> +  string executeDuration = 5;
executeDuration is use for show "时长: 00:00:03"

2021-09-14 07:39 UTC, ZLValien commented on core/dop/autotest/testplan/autotest-plan.proto
> +  string executeDuration = 5;
Preprocessing has been done in AOP in advance, and data is directly forwarded in this interface

2021-09-14 07:43 UTC, Effet approved these changes

2021-09-14 07:44 UTC, Effet commented
/approve

2021-09-14 07:57 UTC, sfwn approved these changes

2021-09-14 07:57 UTC, merged